service:
  name: product-service

#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors:
            origin: '*'
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: products/{productId}
          cors:
            origin: '*'          